version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5555:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
# docker-compose -f docker-compose-pg-only.yml up -d